e - Mark main action as success when all subactions passed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,3 @@
-# .github/workflows/main.yml
-
 name: Action_main
 
 on:
@@ -13,7 +11,6 @@ on:
     types: [completed]
 
 concurrency:
-  # Cancel any in-progress workflows for this workflow/branch combination.
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
@@ -21,9 +18,6 @@ jobs:
   SwiftLint:
     runs-on: ubuntu-latest
     steps:
-      - name: Check Success Status
-        if: ${{ github.event.workflow_run.conclusion == 'success' }}
-        run: echo 'The triggered workflow was successful.'
       - name: Check Failure Status
         if: ${{ github.event.workflow_run.conclusion == 'failure' }}
         run: |
@@ -38,6 +32,19 @@ jobs:
         run: echo 'The triggered workflow was successful.'
       - name: Check Failure Status
         if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: |
+          echo 'The triggered workflow failed.'
+          exit 1
+
+  Main:
+    needs: [SwiftLint, Build]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Success Status
+        if: ${{ needs.SwiftLint.outcome == 'success' && needs.Build.outcome == 'success' }}
+        run: echo 'The triggered workflow was successful.'
+      - name: Check Failure Status
+        if: ${{ needs.SwiftLint.outcome == 'failure' || needs.Build.outcome == 'failure' }}
         run: |
           echo 'The triggered workflow failed.'
           exit 1
